# NumPyの基礎

In [1]:
import numpy as np

## numpy.ndarray(N-dimentional array)
多次元配列の定義

In [2]:
array1d = np.array([1, 2, 3, 4])
array2d = np.array([[11, 12, 13], [21, 22, 23]])

配列の形状

In [3]:
print(array1d.shape)
print(array2d.shape)

# 配列のデータ型
a = np.array([1, 2, 3])
print(a.dtype)

(4,)
(2, 3)
int64


## 配列の生成

In [4]:
a = np.arange(1, 10, 2)
print(a)

b = np.linspace(1, 10, 3)
print(b)

[1 3 5 7 9]
[ 1.   5.5 10. ]


In [5]:
# 適当な形状の配列を生成(3 x 4 x 5の3次元配列)
a = np.random.rand(3, 4, 5)
print(a)
print(a.shape)

[[[0.24374856 0.86387193 0.52440398 0.52099452 0.59770331]
  [0.05532574 0.71561092 0.07853046 0.05241698 0.16567522]
  [0.72376065 0.38969566 0.97211452 0.96931462 0.86368942]
  [0.69311717 0.18670691 0.48523952 0.56975687 0.42427027]]

 [[0.71439747 0.9284766  0.90248792 0.97735066 0.67126925]
  [0.15093086 0.15256603 0.79191611 0.46462587 0.90993391]
  [0.90774315 0.04558914 0.94003608 0.01279647 0.88232343]
  [0.11643179 0.95946054 0.99298353 0.64319506 0.3526564 ]]

 [[0.86671373 0.85888963 0.7055839  0.45934388 0.01741847]
  [0.06281673 0.36837088 0.6143556  0.9521343  0.78077184]
  [0.1920189  0.01196068 0.01337968 0.93456862 0.73926863]
  [0.5268429  0.29148971 0.0205325  0.75960426 0.58253815]]]
(3, 4, 5)


## 配列の操作

### スライシング
配列の一部を取り出す。

In [6]:
a = np.array([1, 2, 3, 4])
print(a[1:3]) # 2番目から3番目の要素を取り出す

[2 3]


### 形状変更
要素数を変えない範囲で形状を変更する。

In [7]:
array23 = np.array([[1, 2, 3], [4, 5, 6]])
print(array23.shape)

# 2行3列の配列を3行2列の配列に変形する
array32 = array23.reshape(3, 2)
print(array32.shape)

# 2行3列の配列を1行6列の配列に変形する
array16 = array23.reshape(1, 6)
print(array16.shape)

(2, 3)
(3, 2)
(1, 6)


### 配列の結合

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
ab = np.concatenate([a, b])
print(ab)

[1 2 3 4 5 6]


## 配列の演算

通常は要素数が同じ配列同士で演算を行う。

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b) # 要素ごとの和
print(a * b) # 要素ごとの積

[5 7 9]
[ 4 10 18]


### ブロードキャスト
異なる形状の配列同士で演算を行う場合、ブロードキャストにより自動的に形状が合わせられる。

In [10]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)
print(b.shape)

print(a + b) # ブロードキャストにより、aがbの形状に合わせて自動的に拡張される

(3,)
(2, 3)
[[2 4 6]
 [5 7 9]]


In [11]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print(a.shape)
print(b.shape)

print(a + b) # ブロードキャストにより、aがbの形状に合わせて自動的に拡張される

(3,)
(3, 1)
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 次元を追加して計算を行うパターン

In [12]:
a = np.random.rand(2, 2, 3)
b = np.random.rand(2, 3)
print(a.shape)
print(b.shape)

# bの先頭に要素1の次元が追加され(1, 2, 3)という形状に変換された後に計算が行われる
c = a + b 
print(c.shape)

(2, 2, 3)
(2, 3)
(2, 2, 3)


次元追加のイメージ

In [13]:
b = np.random.rand(2, 3)
print(b.shape)
print(b)
# bの先頭に1次元追加
b_expanded = b[np.newaxis, :, :]
print(b_expanded.shape)
print(b_expanded)

(2, 3)
[[0.21503393 0.94799165 0.43942452]
 [0.25702066 0.96106448 0.43990902]]
(1, 2, 3)
[[[0.21503393 0.94799165 0.43942452]
  [0.25702066 0.96106448 0.43990902]]]


## 線形代数

内積

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b)) # 内積

32


行列積(行列同士の積)

In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)
b = np.array([[7], [8], [9]])
print(b.shape)
c = np.matmul(a, b) # 行列積
print(c)

(2, 3)
(3, 1)
[[ 50]
 [122]]


特定の次元に関してのみ和を計算

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a_sum1 = np.sum(a, axis=0)
print(a_sum1) # 行方向に和を計算

a_sum2 = np.sum(a, axis=1)
print(a_sum2) # 列方向に和を計算

[5 7 9]
[ 6 15]
